Update cmake-single-platform.yml
Removed test report code as I cant seem to figure out how to generate a junit file.

diff --git a/.github/workflows/cmake-single-platform.yml b/.github/workflows/cmake-single-platform.yml
--- a/.github/workflows/cmake-single-platform.yml
+++ b/.github/workflows/cmake-single-platform.yml
@@ -47,28 +47,14 @@ jobs:
       working-directory: ${{github.workspace}}/build
       # Execute tests defined by the CMake configuration.
       # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
-      run: ctest -C ${{env.BUILD_TYPE}} --output-junit testRes.xml
-
-    - name: Test1
-      working-directory: ${{github.workspace}}/build
-      # Execute tests defined by the CMake configuration.
-      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
-      run: ctest -C ${{env.BUILD_TYPE}} --output-junit testRes.xml
+      run: ctest -C ${{env.BUILD_TYPE}}
         
-    - name: Check_file
-      run: |
-        if [ -f ${{github.workspace}}/build/testRes.xml ]; then
-          echo "File exists"
-        else
-          echo "File does not exist"
-        fi
-        
-    - name: Test Reporter
-      uses: dorny/test-reporter@v1.8.0
-      if: success() || failure()    # run this step even if previous step failed
-      with:
-        name: JEST Tests            # Name of the check run which will be created
-        path: ${{github.workspace}}/build/testRes.xml    # Path to test results
-        reporter: jest-junit        # Format of test results
+    # - name: Test Reporter
+    #   uses: dorny/test-reporter@v1.8.0
+    #   if: success() || failure()    # run this step even if previous step failed
+    #   with:
+    #     name: JEST Tests            # Name of the check run which will be created
+    #     path: ${{github.workspace}}/build/testRes.xml    # Path to test results
+    #     reporter: jest-junit        # Format of test results
           
 
